### ISSUE TITLE
AVAudioSessionCategoryOptionAllowBluetoothHFP regression in 0.11.3

### ISSUE THREAD

**Issue by tamlyn** [software-mansion/react-native-audio-api#945]
### Description

After updating from 0.11.2 to 0.11.3 I get this error when compiling my iOS app using iOS SDK 18.5:

```
› Compiling react-native-audio-api Pods/RNAudioAPI » AudioSessionManager.mm

❌  (node_modules/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm:402:18)

  400 | 
  401 |     if ([option isEqualToString:@"allowBluetoothHFP"]) {
> 402 |       options |= AVAudioSessionCategoryOptionAllowBluetoothHFP;
      |                  ^ use of undeclared identifier 'AVAudioSessionCategoryOptionAllowBluetoothHFP'
  403 |     }
  404 | 
  405 |     if ([option isEqualToString:@"defaultToSpeaker"]) {
```

I believe the problem may have been introduced in #926. A workaround is to switch back to 0.11.2.

### Steps to reproduce

Attempt to build an iOS app with this lib on XCode 16.4, iOS SDK 18.5

### Snack or a link to a repository

n/a

### React Native Audio API version

0.11.3

### React Native version

0.81.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes
