### PR TITLE
feat: update to react native 0.80.0

### LINKED ISSUE #510: Fails to build on Android on react native 0.80
### Description

When building a react native of version 0.80.0 app with `react-native-audio-api` then I get the following error:
```
Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: file:///Users/itsramiel/Desktop/All/Typescript/ReactNative/AudioApiRnEighty/node_modules/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt:15:70 Unresolved reference 'ResourceDrawableIdHelper'.
e: file:///Users/itsramiel/Desktop/All/Typescript/ReactNative/AudioApiRnEighty/node_modules/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt:228:22 Unresolved reference 'instance'. FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':react-native-audio-api:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 4s.
```

### Steps to reproduce

1. clone provided repo
2. run on android
3. observe error

### Snack or a link to a repository

https://github.com/itsramiel/AudioApiRnEighty

### React Native Audio API version

0.6.2-rc.6

### React Native version

0.80.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by itsramiel**
Closes #510

## ⚠️ Breaking changes ⚠️

- Would no longer work with older react native versions?

## Introduced changes

[This commit](https://github.com/facebook/react-native/commit/8de401c62520fc0ef83e820b62e15714dc793b45) which made it to 0.80 changed `ResourceDrawableIdHelper` from singleton class to an object. `Companion.instance` does not work and `instance` is deprecated

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added/Conducted relevant tests
- [x] Performed self-review of the code
- [ ] Updated Web Audio API coverage
- [ ] Added support for web

### CODE REVIEW

File: packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt [hunk 1]
```diff
@@ -225,7 +225,7 @@ class LockScreenManager(
       // If we are running the app in debug mode, the "local" image will be served from htt://localhost:8080, so we need to check for this case and load those images from URL
       if (local && !url.startsWith("http")) {
         // Gets the drawable from the RN's helper for local resources
-        val helper = instance
+        val helper = ResourceDrawableIdHelper
```
Comment (maciejmakowski2003) [inline packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt]: Does it work on previous versions of RN?

**Comment by maciejmakowski2003** [comment]
we will add fix today ;))

File: packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt (hunk 1 above)
Comment (itsramiel) [reply packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt]: This no, but we can use the `instance` for backward compatibility:
https://github.com/facebook/react-native/blob/252e1345bfe890bf786f50af471adcc48995ad35/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ResourceDrawableIdHelper.kt#L68-L71

Comment (itsramiel) [reply packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt]: I can create another pr without the react native upgrade step if you want to isolate the changes.

Comment (maciejmakowski2003) [reply packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt]: I think its okey to leave it here
