### ISSUE TITLE
Compatibility with worklets 0.12.x

### ISSUE THREAD

**Issue by xgiovio** [software-mansion/react-native-audio-api#1250]
### Description

❌  (node_modules/react-native-audio-api/common/cpp/audioapi/core/utils/worklets/WorkletsRunner.cpp:18:18)

  16 | #if RN_AUDIO_API_ENABLE_WORKLETS
  17 |   unsafeRuntimePtr = &strongRuntime->getJSIRuntime();
> 18 |   strongRuntime->executeSync([this, shareableWorklet](jsi::Runtime &rt) -> jsi::Value {
     |                  ^ no member named 'executeSync' in 'worklets::WorkletRuntime'
  19 |     /// Placement new to avoid dynamic memory allocation
  20 |     new (reinterpret_cast<jsi::Function *>(&unsafeWorklet))
  21 |         jsi::Function(shareableWorklet->toJSValue(*unsafeRuntimePtr)

❌  (node_modules/react-native-audio-api/common/cpp/audioapi/core/utils/worklets/WorkletsRunner.cpp:65:25)

  63 |   }
  64 | #if RN_AUDIO_API_ENABLE_WORKLETS
> 65 |   return strongRuntime->executeSync(std::move(job));
     |                         ^ no member named 'executeSync' in 'worklets::WorkletRuntime'
  66 | #else
  67 |   return std::nullopt;
  68 | #endif

### Steps to reproduce

user latest react-native-audio-api with worklets 0.12.x

### Snack or a link to a repository

This is not needed

### React Native Audio API version

latest

### React Native version

0.86.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug app & dev bundle

### Device

None

### Device model

iphone 17 pro max

### Acknowledgements

Yes

**Comment by maciejmakowski2003** [comment]
hi, thanks for reporting that issue. currently we are just around the corner of releasing 1.0.0, which extracts `react-native-worklets` integration to separate package. do you use `react-native-audio-api` x `react-native-worklets integration`?

**Comment by jwatzman** [comment]
Any chance of getting a point release of audio-api to fix this issue, or if not, do you have any ETA on the 1.0.0 release? FWIW, this is blocking us from upgrading to RN 0.87 -- the version of reanimated which supports 0.87 requires a version of worklets which is too new to work with audio-api! So there is no intersection of versions which work with RN 0.87 :(

*Edit*: and, if useful, we do not directly use worklets at all ourselves, just whatever reanimated and/or audio-api might use in their default configuration.

**Comment by maciejmakowski2003** [comment]
Hi, thanks for reaching out. I will take a look at it by the end of the week.

**Comment by jwatzman** [comment]
In case anyone else is running into this and wants a quick-and-dirty workaround, we used `patch-package` to inject a simple one-line change to completely disable worklets since we weren't using them, thus allowing us to upgrade everything:

```

diff --git a/node_modules/react-native-audio-api/scripts/validate-worklets-version.js b/node_modules/react-native-audio-api/scripts/validate-worklets-version.js
index 9d2b0d9..686d203 100644
--- a/node_modules/react-native-audio-api/scripts/validate-worklets-version.js
+++ b/node_modules/react-native-audio-api/scripts/validate-worklets-version.js
@@ -1,4 +1,5 @@
 'use strict';
+process.exit(1);
 
 const semverGte = require('semver/functions/gte');
 ```

**Comment by maciejmakowski2003** [comment]
hey guys, I am going release 0.13.4 early next week with an appropriate fix. here is a branch -> https://github.com/software-mansion/react-native-audio-api/tree/release/0.13.4

**Comment by jwatzman** [comment]
That would be fantastic, thank you!

**Comment by mdydek** [comment]
released in 0.13.4: https://www.npmjs.com/package/react-native-audio-api/v/0.13.4
