### ISSUE TITLE
Fails to build on Android on react native 0.80

### ISSUE THREAD

**Issue by itsramiel** [software-mansion/react-native-audio-api#510]
### Description

When building a react native of version 0.80.0 app with `react-native-audio-api` then I get the following error:
```
Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: file:///Users/itsramiel/Desktop/All/Typescript/ReactNative/AudioApiRnEighty/node_modules/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt:15:70 Unresolved reference 'ResourceDrawableIdHelper'.
e: file:///Users/itsramiel/Desktop/All/Typescript/ReactNative/AudioApiRnEighty/node_modules/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt:228:22 Unresolved reference 'instance'. FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':react-native-audio-api:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 4s.
```

### Steps to reproduce

1. clone provided repo
2. run on android
3. observe error

### Snack or a link to a repository

https://github.com/itsramiel/AudioApiRnEighty

### React Native Audio API version

0.6.2-rc.6

### React Native version

0.80.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes
